DROP TABLE noteReferences;
DROP TABLE notes;
DROP TABLE attachments;
DROP TABLE lectures;
DROP TABLE sections;
DROP TABLE tasks;
DROP TABLE courses;
DROP TABLE semesters;

CREATE TABLE semesters
(semesterID	VARCHAR PRIMARY KEY,
 semesterNr	INTEGER);

CREATE TABLE courses
(courseID	VARCHAR PRIMARY KEY,
 name		VARCHAR(128) NOT NULL,
 relatedTo	VARCHAR REFERENCES semesters ON DELETE CASCADE);

CREATE TABLE tasks
(taskID		VARCHAR PRIMARY KEY,
 deadline	VARCHAR(16),
 content		VARCHAR(128) NOT NULL,
 relatedTo	VARCHAR REFERENCES courses ON DELETE CASCADE);

CREATE TABLE sections
(sectionID	VARCHAR PRIMARY KEY,
 name		VARCHAR(64),
 lecturer	VARCHAR(64),
 relatedTo	VARCHAR REFERENCES courses ON DELETE CASCADE);

CREATE TABLE lectures
(lectureID	VARCHAR PRIMARY KEY,
 roomNr		VARCHAR(32),
 startTime	VARCHAR(16),
 endTime		VARCHAR(16),
 lectureNr	INTEGER,
 relatedTo	VARCHAR REFERENCES sections ON DELETE CASCADE);

CREATE TABLE notes
(noteID		VARCHAR PRIMARY KEY,
 title 		VARCHAR(64),
 content    VARCHAR,
 relatedTo	VARCHAR REFERENCES lectures ON DELETE CASCADE);

CREATE TABLE noteReferences
(referenceID	VARCHAR PRIMARY KEY,
 row		INTEGER,
 noteID		VARCHAR REFERENCES notes ON DELETE CASCADE);


CREATE TABLE attachments
(attachmentID	VARCHAR PRIMARY KEY,
 content		VARCHAR,
 relatedTo	VARCHAR REFERENCES lectures ON DELETE CASCADE);
